### PR TITLE
recipes-graphics: libdrm: remove useless patch

### PR DESCRIPTION
**Pull request by sbourdelin**
This patch is now available upstream [1] and are introduce in the
meta-freescale layer for the thud branch [2]

 [1] https://source.codeaurora.org/external/imx/libdrm-imx/commit/?h=libdrm-imx-2.4.91&id=e8e9cf8a66be11508c39f1cc31b8a5e7eb758875
 [2] https://github.com/Freescale/meta-freescale/commit/990ec30a581886d97caa96b436858cab7130197a#diff-787a1d77c64e601d735cc848c3fbb5cc

### CODE REVIEW

**Comment by sbourdelin** [comment]
ping?

**Comment by eranmati** [comment]
Hi Sebastien.
Sorry for the long delay.
We have a lot on our plate at the moment so it takes a little time, but we will have an official Thud release soon (and we will review and test your patch).

Thanks,
Eran

**Comment by sbourdelin** [comment]
Hi @eranmati, sure!
Good news for the official Thud release, keep it up guys :)

Thanks,
Sebastien.

**Comment by sbourdelin** [comment]
Hi @eranmati, Thanks for the commit https://github.com/varigit/meta-variscite-fslc/commit/824f61732322b6dba97873db76abff3ab7f5d03a

However, it would have been great to accept my commit instead of creating an other one which does exactly the same...
It will encourage the community to send patches and reported issues if you keep their name in your repository :)

**Comment by varigigi** [comment]
Hi @sbourdelin,
I bag your pardon for not accepting your patch, it's not my intention discourage community to send patches.
The commit [824f617](https://github.com/varigit/meta-variscite-fslc/commit/824f61732322b6dba97873db76abff3ab7f5d03a) was in my queue since August 2018, when Otavio integrated my patch to meta-freescale:
   https://github.com/Freescale/meta-freescale/commit/063154a7783aeafd299739c450e9fef754ead7a8
However I kept postponing it, waiting for a manifest refresh.
Sorry
BR
Pier

**Comment by sbourdelin** [comment]
Hi @varigigi,

No problem at all, thanks for the quick reply and the explanation! :)

Best Regards,
Sebastien

**Pull request closed without merging**
