### PR TITLE
linux-variscite_4.1.15.bb: Dont use uppercase in PR

### PR DESCRIPTION
**Pull request by kraj**
opkg backend only allows lowercase letters in PR
therefore change LOCALVERSION values accordingly.

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
This helps in using this branch with pyro and master of core layer

**Comment by kraj** [comment]
any update on thisa PR?

**Comment by eranmati** [comment]
Hi Khem.
Thanks for the input.
We will review everything, but it will take some time, as we have other priorities.

Regards,
Eran

**Comment by kraj** [comment]
rebased on top of latest morty

**Comment by kraj** [comment]
superseded  by https://github.com/varigit/meta-variscite-fslc/pull/3

**Pull request closed without merging**
