### PR TITLE
Patches to make it work with OE-Core master

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by eranmati** [comment]
The u-boot-fw-utils and bluez5 patches are no longer needed.

**Comment by kraj** [comment]
@eranmati yes I missed that in rebase. I have now removed these two commits.

**Comment by kraj** [comment]
I have updated these on top of latest pyro

**Comment by kraj** [comment]
@eranmati do you see any issues with these two patches ? this will make your layer work with oe/master, let me know if you are not interested, I can stop sending these pull requests and maintain a community fork and advertise that to OE community.

**Comment by kraj** [comment]
@eranmati no, fragments is not needed for master, but its needed for community, who takes your SOM and embeds it into their boards, and need to tweak default config a little, right now they have
to copy the whole defconfig and are them left out of any changes that happens upstream. Its a real problem.

**Comment by eranmati** [comment]
The U-Boot patch is redundant since commit 3ef43ed6e378ec29f6ee2a5b9e13bd8fea074a7b from Oct 15.
The Linux patch is redundant since commit 38d8f87eb3699fe0743d8ba0e66bc46328693700 (in the rocko branch).

Thanks.

**Pull request closed without merging**
