### PR TITLE
Update linux-firmware_%.bbappend

### PR DESCRIPTION
**Pull request by murat-dogan**
TI git server is down. Replace with the https alternative.

### CODE REVIEW

**Comment by murat-dogan** [comment]
Please note that revisions are not used.
```
SRCREV_tiwlan = "bda5304cc86e9c4029f8101394d2a8b39c640f53"
BRANCH_tiwlan = "master"
SRCREV_tibt = "3aa1d75f3c2ae77f6e4d36194e3d281b899ab149"
BRANCH_tibt = "master"
```

**Comment by varigigi** [comment]
Hi @murat-dogan,
moving to https protocol may be a good idea to bypass some company firewall preventing git communications. but can you please clarify the testing conditions?
From time to time, we have already observed sporadic down-time of TI server, but when this happen the communication protocol is not relevant at all.
Thanks
Best Regards
Pier

**Comment by murat-dogan** [comment]
Hi @varigigi ,
Last 2-3 days I have tried to download the package by using git protocol with no chance. 
But https was working.

As you said it is more flexible.

I am in a corporate network but git protocol is not prevented. I can clone other packages (not from ti)

**Comment by varigigi** [comment]
Hi @murat-dogan,
at least when you opened this PR, git protocol was (and is still) working just out of the box on my side.
I'll be glad to accept your PR if you change the comment in the commit to refer https flexibility and remove *ti git server is down*.
Thanks
Best Regards
Pier

**Comment by murat-dogan** [comment]
I will create a new PR

**Pull request closed without merging**
